
version: 2

groups:
  - name: consolidation
    owner: 
      name: consolidation team
      email: consolidation@outlook.com

models:
  - name: test1
    description: "A starter dbt model"
    group: consolidation
    access: public
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: test2
    description: "A starter dbt model"
    group: consolidation
    access: private
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
